# Generated by Django 4.1 on 2022-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
