# Generated by Django 4.1 on 2022-08-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='hash',
            field=models.URLField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='original_url',
            field=models.URLField(),
        ),
    ]
